apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodejs-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.deploymentStrategy.type }}
  selector:
    matchLabels:
      app: {{ include "nodejs-service.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "nodejs-service.fullname" . }}
    spec:
      containers:
      - name: {{ include "nodejs-service.fullname" . }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: service-port
            containerPort: {{ .Values.service.port }}
            protocol: TCP
        readinessProbe:
          initialDelaySeconds: 25
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: {{ .Values.service.port }}
        resources:
        {{- toYaml .Values.resources | nindent 10 }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}