apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-nodeport" (include "nodejs-service.name" .) }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "nodejs-service.fullname" . }}
  ports:
    - name: service
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
